### ISSUE TITLE
Console being spammed with messages

### ISSUE THREAD

**Issue by ShmoopyDoo** [Xratedjunior/Better-Default-Biomes#13]
Our console is getting nearly nonstop spam, I'm not sure how to elaborate on this further so here's a snippet via pastebin-
https://pastebin.com/VaWPtRC2

Running via Life in the Village 2 modpack

**Comment by Xratedjunior** [comment]
Sorry about that. Thanks for letting me know! Will be fixed in the next update.

**Comment by zlainsama** [comment]
When will the fix for this be released?

**Comment by Xratedjunior** [comment]
In the next update. I had to finish some stuff for school, but I'm updating to the latest version of forge at the moment and I hope to finish the update soon
