### ISSUE TITLE
Foliage fails to generate with BDB on HDDs

### ISSUE THREAD

**Issue by Drakoflame** [Xratedjunior/Better-Default-Biomes#20]
Using the Engineers Life 2 Modpack.
Sometimes (more often than not) Foliage from Vanilla and a few other mods refuse to generate when creating a world. BDB, Simple Farming, and Terra Incognita foliage/decorations _will_ spawn, but other trees and foliage do not.

We did some extensive testing to try and figure out what the cause (at least, to figure out which mod was the issue) of foliage not spawning, and we narrowed it down to BDB. One of the Pack Devs, Czbüendel, was unable to reproduce the bug, until we got down to talking about install locations and hardware. Cz is running his instances of the pack off of an SSD, where as me and two other players are running on HDDs, and only the three of us were encountering the issue, though like I said _sometimes_ things would work normally, but we're unsure what the difference was that allowed the generation of trees and other decor.

I'm going to include two log files. The worlds tested were done using the same seed: "-7006285537956092991", with the reference location begin to the NorthNorthWest direction, a hill that is covered in birch and oak trees. With BDB, the hill would be bare, and the plains below it devoid of grass. Without BDB, the hill was populated with trees, and the grass in the plains was plentiful.

This is a brand new fresh install using the world seed, no foliage spawned
[2021-05-23-3.log.gz](https://github.com/Xratedjunior/Better-Default-Biomes/files/6527833/2021-05-23-3.log.gz)

This is the log after re-enabling BDB, and dissabling Terra Incognita (to test if it was also causing the issues, which it did not)
[2021-05-23-1.log.gz](https://github.com/Xratedjunior/Better-Default-Biomes/files/6527836/2021-05-23-1.log.gz)

I hope that you're able to look at these logs and potentially figure out what might be causing the issue, and a fix can be made shortly, so that people can go back to not having to rely on RNG to have foliage in their worlds or not xD

**Comment by czbuendel** [comment]
We experienced an issue similar to this that pointed to Supplementaries way signs here (https://github.com/MehVahdJukaar/Supplementaries/issues/57).
A blame report specifically pointed to that mod in that case.

We referenced this issues (https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/75) there to help.

**Comment by czbuendel** [comment]
I pulled the following blame section from one of Drako's logs.
[blame.txt](https://github.com/Xratedjunior/Better-Default-Biomes/files/6527872/blame.txt)
It was preceded by these log lines.
[BiomeGenerationSettings.txt](https://github.com/Xratedjunior/Better-Default-Biomes/files/6527877/BiomeGenerationSettings.txt)

I really don't know what the issue could be because I can never replicate the issue myself. We were finally able to find that seed above in the pack that managed to get repeatable results.

**Comment by Xratedjunior** [comment]
I am reworking the way I register the Biome generation which will hopefully fix all these types of bugs in the future.
Sadly it is the reason why this update is taking so long to finish. As well as me trying to finish school.

However, I'm trying to get it out and it will hopefully fix it all.

**Comment by czbuendel** [comment]
Thank you for your work, just finished up my final semester of school as well.

**Comment by Xratedjunior** [comment]
Should be fixed in later versions of the mod
