### ISSUE TITLE
Desert bandit spawning

### ISSUE THREAD

**Issue by someaddons** [Xratedjunior/Better-Default-Biomes#21]
It would be nice if the Desert bandits could avoid spawning in broad light, like other mobs do, so that you can actually live in a desert without having spawns all the time

**Comment by Xratedjunior** [comment]
I will think of a way to fix this

**Comment by helpfulchicken** [comment]
this is a problem for me too, I play with MineColonies and I can't seem to stop bandits spawning.

**Comment by theArhar** [comment]
I am playing TNP Limitless 3 and they are annoying in my trading village

**Comment by Xratedjunior** [comment]
Fixed from version 1.18 and up
