### ISSUE TITLE
Feeding Ducks

### ISSUE THREAD

**Issue by DoctorMage** [Xratedjunior/Better-Default-Biomes#26]
Similiar to the zebra issue posted back in january
If you right clikc a duck with anything it will consume it
Modpack: Engineers Life 1.09 By dreams01
Proof 
https://streamable.com/3ueobm
Version of the mod: BetterDefaultBiomes-1.16.4+-Alpha 2.5.3

Log
[latest.log](https://github.com/Xratedjunior/Better-Default-Biomes/files/7574777/latest.log)

**Comment by Xratedjunior** [comment]
Thanks for the feedback! However, this is fixed in Alpha 2.6.0
