### ISSUE TITLE
Scout Enchantment cannot be applied to Helmets with Anvils in Survival play

### ISSUE THREAD

**Issue by KnightCa** [Xratedjunior/Better-Default-Biomes#28]
Minecraft version: 1.16.5
Better Default Biomes version: -1.16.4+-Alpha 2.6.1
Life in the Village 2 modpack version: 1.32
Server: Happens on both Multiplayer Server and Singleplayer play.

While in Creative mode, Anvil allows the Scout Enchantment to be placed on Helmets.
When switching to Survival mode, Anvil does not allow the Scout Enchantment to be placed on Helmets.

In earlier Survival play, we were able to use the Anvil to apply this enchantment in Survival.

**Comment by Xratedjunior** [comment]
Is the enchantment maybe disabled in the config?

**Comment by Xratedjunior** [comment]
I have no problems in Survival.
And is exactly what I experience when I turn the Scout Enchantment off in the config.
