### ISSUE TITLE
Short grass spawns on mycelium

### ISSUE THREAD

**Issue by DarkXFast** [Xratedjunior/Better-Default-Biomes#30]
![2022-06-23_16 38 13](https://user-images.githubusercontent.com/19753158/175313186-925db81a-31ad-41de-9354-34d9664970b2.png)

**Comment by Xratedjunior** [comment]
Thank you for letting me know! I've never noticed this before

**Comment by Xratedjunior** [comment]
Fixed in latest 1.20.2 update
