### ISSUE TITLE
Better Default Biomes Crash

### ISSUE THREAD

**Issue by 704Prod** [Xratedjunior/Better-Default-Biomes#31]
BDB Causing crashes for SOME people who download my modpack
Modpack Link [[Charlotte Craft](https://www.curseforge.com/minecraft/modpacks/charlotte-craft-704craft-mmorpg)](url)

Crash Log
https://pastebin.com/asxhnY0v

Latest (Pasted to ControlC because it was too long for Pastebin)
https://controlc.com/f04a89aa

**Comment by Xratedjunior** [comment]
Caused by another mod

**Comment by dr3ams** [comment]
Which mod caused it? Had the same error

**Comment by Xratedjunior** [comment]
> Which mod caused it? Had the same error

It turned out to be Twilight Forest. Something about matching item IDs.
I got told in the Discord so I haven't done any testing myself.
