### ISSUE TITLE
When a zombie spawner occurs in a Taiga, zombies won't spawn

### ISSUE THREAD

**Issue by coderepo8593** [Xratedjunior/Better-Default-Biomes#32]
This mod is preventing normal zombies from spawning in a spawner when in the Taiga biome. This behavior should only prevent zombie spawns in the world, not altogether from spawners. It does successfully replace them with Frozen Zombies, but it doesn't work with the spawners and instead prevents their spawning.

**Comment by coderepo8593** [comment]
Closing This issue, it was being caused by something else and not this mod.

**Comment by Xratedjunior** [comment]
Indeed, the mod only removes natural Zombie spawns from Biomes. :)
