### ISSUE TITLE
BDB has failed to load correctly, java.lang.NullPointerException; null

### ISSUE THREAD

**Issue by HolyKnight9320** [Xratedjunior/Better-Default-Biomes#34]
After waiting for Forge to load the game it popped up with "Error loading mods". I am not sure how to fix the issue.

![Screenshot 2023-04-12 145023](https://user-images.githubusercontent.com/130607308/231581775-f10b7f27-a9c7-4a51-9e56-1f44ec9190cf.jpg)

**Comment by Xratedjunior** [comment]
@HolyKnight9320 I need the crashlog to figure out what happened.

**Comment by notlin4** [comment]
Please go to Prism Launcher "Settings" -> "API" -> "API Key". 
In the "CurseForge Core API" field, enter: `$2a$10$bL4bIL5pUWqfcO7KQtnMReakwtfHbNKh6v1uTpKlzhwoueEJQnPnm`, and then reinstall the modpack/mod.

**Comment by notlin4** [comment]
@Xratedjunior Why was my message marked as off-topic? That's its resolution method.
