### ISSUE TITLE
Planks not tagged as such?

### ISSUE THREAD

**Issue by Aceplante** [Xratedjunior/Better-Default-Biomes#36]
swamp willow for example does not seem to be able to be used to craft chests, jukeboxes, or other plank things. I am assuming its not tagged as planks, an issue that likely applies to other woods as well

forge 1.16.5

**Comment by Xratedjunior** [comment]
I'm assuming you're playing with a modpack that changed the recipes perhaps. Because, everything is tagged correctly and I have never heard of this bug before.

**Comment by Xratedjunior** [comment]
Let me know if it works for you if you use the mod on its own
