### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by CraftyZombie** [Xratedjunior/Better-Default-Biomes#38]
With only BetterDefaultBiomes Alpha 5.0.3 (1.20.1) installed on a server, a crash occurs.
[latest.log](https://github.com/Xratedjunior/Better-Default-Biomes/files/13942037/latest.log)
[debug.log](https://github.com/Xratedjunior/Better-Default-Biomes/files/13942042/debug.log)
[crash-2024-01-15_10.27.07-fml.txt](https://github.com/Xratedjunior/Better-Default-Biomes/files/13942044/crash-2024-01-15_10.27.07-fml.txt)

**Comment by Xratedjunior** [comment]
Thank you, I will fix it ASAP!

**Comment by CraftyZombie** [comment]
Of course. Thank you!

**Comment by Xratedjunior** [comment]
Should be fixed as of:
Alpha 5.0.3.1

Enjoy!
