### ISSUE TITLE
zh_tw file

### ISSUE THREAD

**Issue by ghost** [Xratedjunior/Better-Default-Biomes#4]
I translated the mod.

{
	//ItemGroups
	"itemGroup.betterdefaultbiomes": "Better Default Biomes",
	
	//Advancements
	"advancements.betterdefaultbiomes.root.description": "安裝"Better Default Biomes"後開始遊戲.",
	"advancements.betterdefaultbiomes.frozen_flesh.title": "不得已",
	"advancements.betterdefaultbiomes.frozen_flesh.description": "吃冰凍腐肉.",
	"advancements.betterdefaultbiomes.this_is_new.title": "全新",
	"advancements.betterdefaultbiomes.this_is_new.description": "開始探索時間.",
	"advancements.betterdefaultbiomes.kill_all_mobs.title": "大規模狩獵",
	"advancements.betterdefaultbiomes.kill_all_mobs.description": "殺死全部生物.",
	"advancements.betterdefaultbiomes.axe_feather_reed_grass.title": "小麥",
	"advancements.betterdefaultbiomes.axe_feather_reed_grass.description": "用斧頭破壞拂子草.",
	"advancements.betterdefaultbiomes.eat_all_foods.title": "額外食物",
	"advancements.betterdefaultbiomes.eat_all_foods.description": "吃掉BDB添加的所有食物.",
	
	//Old Advancements
	"advancements.betterdefaultbiomes.killed_by_hunter.title": "狩獵",
	"advancements.betterdefaultbiomes.killed_by_hunter.description": "殺死獵人.",
	"advancements.betterdefaultbiomes.shoot_a_hunter.title": "以牙還牙",
	"advancements.betterdefaultbiomes.shoot_a_hunter.description": "射死獵人.",
	"advancements.betterdefaultbiomes.killed_by_jungle_creeper.title": "隱形的跟蹤狂",
	"advancements.betterdefaultbiomes.killed_by_jungle_creeper.description": "被叢林爬行者炸死.",
	"advancements.betterdefaultbiomes.kill_a_jungle_creeper.title": "不是現在!",
	"advancements.betterdefaultbiomes.kill_a_jungle_creeper.description": "殺死一個叢林苦力帕.",
	
	//Enchantments
	"enchantment.betterdefaultbiomes.smelting_touch": "冶煉之觸",
	"enchantment.betterdefaultbiomes.smelting_touch.desc": "採礦時冶煉礦物.",
	"enchantment.betterdefaultbiomes.scout": "偵查",
	"enchantment.betterdefaultbiomes.scout.desc": "使玩家一定範圍內的生物發光.",
	"enchantment.betterdefaultbiomes.hunting": "狩獵",
	"enchantment.betterdefaultbiomes.hunting.desc": "對動物造成更多傷害.",
	"enchantment.betterdefaultbiomes.horse_protection": "馬的保護",
	"enchantment.betterdefaultbiomes.horse_protection.desc": "馬獲得保護.",
	"enchantment.betterdefaultbiomes.horse_fire_protection": "馬的抗火性",
	"enchantment.betterdefaultbiomes.horse_fire_protection.desc": "馬獲得抗火性.",
	"enchantment.betterdefaultbiomes.horse_feather_falling": "馬的緩降",
	"enchantment.betterdefaultbiomes.horse_feather_falling.desc": "馬獲得緩降",
	"enchantment.betterdefaultbiomes.horse_blast_protection": "馬的爆炸保護",
	"enchantment.betterdefaultbiomes.horse_blast_protection.desc": "馬獲得爆炸保護.",
	"enchantment.betterdefaultbiomes.horse_projectile_protection": "馬的投射物保護",
	"enchantment.betterdefaultbiomes.horse_projectile_protection.desc": "馬獲得投射物保護.",
	"enchantment.betterdefaultbiomes.spikes": "尖刺",
	"enchantment.betterdefaultbiomes.spikes.desc": "使用盾時刺傷對方.",
	"enchantment.betterdefaultbiomes.guard": "防衛",
	"enchantment.betterdefaultbiomes.guard.desc": "使用盾時擊退對方.",
	"enchantment.betterdefaultbiomes.floating": "輕功",
	"enchantment.betterdefaultbiomes.floating.desc": "馬在水面上漂浮.",
	
	//Item Tooltips
	"tooltip.betterdefaultbiomes.hold_shift": "按 Shift 獲取更多資訊.",
	"tooltip.betterdefaultbiomes.bandit_arrow": "這是強盜射手的掉落物.",
	"tooltip.betterdefaultbiomes.hunter_arrow": "這是獵人的掉落物.",
	"tooltip.betterdefaultbiomes.torch_arrow": "碰到方塊時放置火把",
	
    //Arrows
	"item.betterdefaultbiomes.hunter_arrow": "獵人之箭",
	"item.betterdefaultbiomes.bandit_arrow": "強盜之箭",
	"item.betterdefaultbiomes.torch_arrow": "火把箭",
	
	"item.betterdefaultbiomes.duck_egg": "鴨蛋",
	
	//Food
    "item.betterdefaultbiomes.frozen_flesh": "冰凍腐肉",
    "item.betterdefaultbiomes.duck": "鴨肉",
    "item.betterdefaultbiomes.cooked_duck": "烤鴨肉",
    "item.betterdefaultbiomes.frog_leg": "蛙腿",
    "item.betterdefaultbiomes.cooked_frog_leg": "烤蛙腿",
    
	//Mob Equipment
    "equipment.betterdefaultbiomes.hunter_bow": "獵人箭",
    "equipment.betterdefaultbiomes.head_hunter_bow": "獵人箭",
    "equipment.betterdefaultbiomes.miner_pickaxe": "礦工鎬",
    "equipment.betterdefaultbiomes.miner_helmet": "礦工頭盔",
    "equipment.betterdefaultbiomes.bandit_sword": "強盜箭",
    "equipment.betterdefaultbiomes.bandit_bow": "強盜箭",
    "equipment.betterdefaultbiomes.bandit_crossbow": "強盜弩",
    "equipment.betterdefaultbiomes.bandit_master_sword": "強盜王箭",
	"equipment.betterdefaultbiomes.robin_hood_bow": "羅賓箭",
	
	//Entities
	"entity.betterdefaultbiomes.hunter": "獵人",
	"entity.betterdefaultbiomes.head_hunter": "獵人首領",
	"entity.betterdefaultbiomes.jungle_creeper": "叢林苦力帕",
	"entity.betterdefaultbiomes.lost_miner": "迷失礦工",
	"entity.betterdefaultbiomes.frozen_zombie": "凍屍",
	
	"entity.betterdefaultbiomes.desert_bandit": "強盜",
	"entity.betterdefaultbiomes.desert_bandit_archer": "強盜射手",
	"entity.betterdefaultbiomes.desert_bandit_arbalist": "強盜刺客",
	"entity.betterdefaultbiomes.desert_bandit_master": "強盜王",
	
		//Passive
		"entity.betterdefaultbiomes.muddy_pig": "泥豬",
		"entity.betterdefaultbiomes.camel": "駱駝",
		"entity.betterdefaultbiomes.duck": "鴨子",
		"entity.betterdefaultbiomes.zebra": "斑馬",
		"entity.betterdefaultbiomes.frog": "青蛙",
		"entity.betterdefaultbiomes.waterbuck": "水鹿",

	"entity.betterdefaultbiomes.robin_hood": "羅賓漢",
	"entity.betterdefaultbiomes.robin_hood_archer": "羅賓漢",
	"entity.betterdefaultbiomes.robin_hood_tanker": "羅賓漢",
	"entity.betterdefaultbiomes.robin_hood_swordsman": "羅賓漢",
	
	//Entity Spawn Eggs
	"item.betterdefaultbiomes.hunter_spawn_egg": "獵人生怪蛋",
	"item.betterdefaultbiomes.head_hunter_spawn_egg": "獵人首領生怪蛋",
	"item.betterdefaultbiomes.jungle_creeper_spawn_egg": "叢林苦力帕生怪蛋",
	"item.betterdefaultbiomes.warthog_spawn_egg": "疣豬生怪蛋",
	"item.betterdefaultbiomes.lost_miner_spawn_egg": "迷失礦工生怪蛋",
	"item.betterdefaultbiomes.frozen_zombie_spawn_egg": "凍屍生怪蛋",
	
	"item.betterdefaultbiomes.desert_bandit_spawn_egg": "強盜生怪蛋",
	"item.betterdefaultbiomes.desert_bandit_archer_spawn_egg": "強盜射手生怪蛋",
	"item.betterdefaultbiomes.desert_bandit_arbalist_spawn_egg": "強盜刺客生怪蛋",
	"item.betterdefaultbiomes.desert_bandit_master_spawn_egg": "強盜王生怪蛋",
	
		//passive
		"item.betterdefaultbiomes.muddy_pig_spawn_egg": "泥豬生怪蛋",
		"item.betterdefaultbiomes.camel_spawn_egg": "駱駝生怪蛋",
		"item.betterdefaultbiomes.duck_spawn_egg": "鴨子生怪蛋",
		"item.betterdefaultbiomes.zebra_spawn_egg": "斑馬生怪蛋",
		"item.betterdefaultbiomes.frog_spawn_egg": "青蛙生怪蛋",
		"item.betterdefaultbiomes.waterbuck_spawn_egg": "水鹿生怪蛋",
	
	"item.betterdefaultbiomes.robin_hood_spawn_egg": "羅賓漢生怪蛋",
	"item.betterdefaultbiomes.robin_hood_archer_spawn_egg": "羅賓漢射手生怪蛋",
	"item.betterdefaultbiomes.robin_hood_tanker_spawn_egg": "羅賓漢坦克生怪蛋",
	"item.betterdefaultbiomes.robin_hood_swordsman_spawn_egg": "羅賓漢劍士生怪蛋",
	
	//Entity Sounds
	"betterdefaultbiomes.subtitle.duck.hurt": "鴨子受傷",
	"betterdefaultbiomes.subtitle.duck.hurt.baby": "幼年鴨子受傷",
	"betterdefaultbiomes.subtitle.duck.death": "鴨子死亡",
	"betterdefaultbiomes.subtitle.duck.death.baby": "幼年鴨子死亡",
	"betterdefaultbiomes.subtitle.duck.ambient": "鴨子嘎嘎",
	"betterdefaultbiomes.subtitle.zebra.hurt": "斑馬受傷",
	"betterdefaultbiomes.subtitle.zebra.death": "斑馬死亡",
	"betterdefaultbiomes.subtitle.zebra.ambient": "斑馬嘶鳴",
	"betterdefaultbiomes.subtitle.frog.hurt": "青蛙受傷",
	"betterdefaultbiomes.subtitle.frog.death": "青蛙死亡",
	"betterdefaultbiomes.subtitle.frog.ambient": "青蛙呱呱",
	
	//Flowers
	"block.betterdefaultbiomes.blue_poppy": "藍罌粟",
	"block.betterdefaultbiomes.dark_violet": "暗紫羅蘭",
	"block.betterdefaultbiomes.purple_verbena": "紫馬鞭草",
	"block.betterdefaultbiomes.pink_cactus_flower": "粉色仙人掌花",
	
	//Potted Flowers
	"block.betterdefaultbiomes.potted_blue_poppy": "盆中的藍罌粟",
	"block.betterdefaultbiomes.potted_dark_violet": "盆中的暗紫羅蘭",
	"block.betterdefaultbiomes.potted_purple_verbena": "盆中的紫馬鞭草",
	"block.betterdefaultbiomes.potted_pink_cactus_flower": "盆中的粉色仙人掌花",
	
	//Mushrooms
	"block.betterdefaultbiomes.white_mushroom": "白蘑菇",
	"block.betterdefaultbiomes.yellow_mushroom": "黃蘑菇",
	"block.betterdefaultbiomes.gray_mushroom": "灰蘑菇",
	
    //Tall Flowers
	
    //Vines
    
    //Plants
	"block.betterdefaultbiomes.feather_reed_grass": "拂子茅",
	"block.betterdefaultbiomes.dead_grass": "死草",
	"block.betterdefaultbiomes.short_grass": "短草",
	"block.betterdefaultbiomes.dune_grass": "沙草",
	
    //Tall Plants
    "block.betterdefaultbiomes.tall_water_reeds": "蘆葦",
    
    //Potted Plants
	"block.betterdefaultbiomes.potted_white_mushroom": "盆中的白蘑菇",
	"block.betterdefaultbiomes.potted_yellow_mushroom": "盆中的黃蘑菇",
	"block.betterdefaultbiomes.potted_gray_mushroom": "盆中的灰蘑菇",
	"block.betterdefaultbiomes.potted_animal_grass": "盆中的牧草",
	"block.betterdefaultbiomes.potted_dead_grass": "盆中的死草",
	"block.betterdefaultbiomes.potted_short_grass": "盆中的短草",
	
	//Trees
    "block.betterdefaultbiomes.palm_sapling": "棕櫚木樹苗",
    "block.betterdefaultbiomes.palm_sapling_potted": "盆中的沼澤柳木樹苗",
    "block.betterdefaultbiomes.palm_leaves": "棕櫚木樹葉",
    "block.betterdefaultbiomes.palm_log": "棕櫚木原木",
    "block.betterdefaultbiomes.palm_wood": "棕櫚木木塊",
    "block.betterdefaultbiomes.palm_log_stripped": "剝皮棕櫚木原木",
    "block.betterdefaultbiomes.palm_wood_stripped": "剝皮棕櫚木木塊",
    "block.betterdefaultbiomes.palm_planks": "棕櫚木木材",
    "block.betterdefaultbiomes.palm_stairs": "棕櫚木階梯",
    "block.betterdefaultbiomes.palm_slab": "棕櫚木半磚",
    "block.betterdefaultbiomes.palm_fence": "棕櫚木柵欄",
    "block.betterdefaultbiomes.palm_fence_gate": "棕櫚木柵欄門",
    "block.betterdefaultbiomes.palm_door": "棕櫚木門",
    "block.betterdefaultbiomes.palm_trapdoor": "棕櫚木地板門",
    "block.betterdefaultbiomes.palm_pressure_plate": "棕櫚木壓力板",
    "block.betterdefaultbiomes.palm_button": "棕櫚木按鈕",
    "block.betterdefaultbiomes.palm_ladder": "棕櫚木梯子",
	"block.betterdefaultbiomes.palm_crafting_table": "棕櫚樹工作台",
   
    
    "block.betterdefaultbiomes.swamp_willow_sapling": "沼澤柳木樹苗",
    "block.betterdefaultbiomes.swamp_willow_sapling_potted": "盆中的沼澤柳木樹苗",
    "block.betterdefaultbiomes.swamp_willow_leaves": "沼澤柳木樹葉",
    "block.betterdefaultbiomes.swamp_willow_log": "沼澤柳木原木",
    "block.betterdefaultbiomes.swamp_willow_wood": "沼澤柳木木塊",
    "block.betterdefaultbiomes.swamp_willow_log_stripped": "剝皮沼澤柳木原木",
    "block.betterdefaultbiomes.swamp_willow_wood_stripped": "剝皮沼澤柳木木塊",
    "block.betterdefaultbiomes.swamp_willow_planks": "沼澤柳木木材",
    "block.betterdefaultbiomes.swamp_willow_stairs": "沼澤柳木階梯",
    "block.betterdefaultbiomes.swamp_willow_slab": "沼澤柳木半磚",
    "block.betterdefaultbiomes.swamp_willow_fence": "沼澤柳木柵欄",
    "block.betterdefaultbiomes.swamp_willow_fence_gate": "沼澤柳木柵欄門",
    "block.betterdefaultbiomes.swamp_willow_door": "沼澤柳木門",
    "block.betterdefaultbiomes.swamp_willow_trapdoor": "沼澤柳木地板門",
    "block.betterdefaultbiomes.swamp_willow_pressure_plate": "沼澤柳木壓力板",
    "block.betterdefaultbiomes.swamp_willow_button": "沼澤柳木按鈕",
    "block.betterdefaultbiomes.swamp_willow_ladder": "沼澤柳木梯子",
    "block.betterdefaultbiomes.swamp_willow_crafting_table": "沼澤柳木工作台"
}

**Comment by Xratedjunior** [comment]
Awesome thank you. I will work it into the next update

**Comment by Xratedjunior** [comment]
Thank you again. Added in version 2.5.2 and this file is now also visible on the github page.
