### ISSUE TITLE
Adding mobs to nether with config does not work

### ISSUE THREAD

**Issue by NixityNull** [Xratedjunior/Better-Default-Biomes#5]
Adding "nether' or nether biome ids doesn't work. I suspect that it is because the nether is turned off for all the mobs spawning but is only configurable for the lost miner.

**Comment by Xratedjunior** [comment]
Nether is not turned off for the mobs, but all the mobs have certain criteria for spawning. I think that's obstructing the mobs from spawning. However, I will check it.

**Comment by NixityNull** [comment]
I am trying to put the jungle creeper in a modded nether biome from biomes o' plenty. Do you know what might be causing it not to spawn? Here's my config for reference: 


#World Spawning and Generation options for Better Default Biomes.
[World]

	#Turn off world generation features in Better Default Biomes.
	[World.Generation]

		[World.Generation.Trees]
			Palm_Trees = false
			Swamp_Willow_Trees = false

		[World.Generation.Plants]
			Feather_Reed_Grass = false
			Dead_Grass = true
			Dune_Grass = true
			Short_Grass = true
			Tall_Water_Reeds = false

		[World.Generation.Flowers]
			Blue_Poppy = true
			Mushrooms = true
			Pink_Cactus_Flower = true
			Purple_Verbena = true
			Dark_Violet = true

	#Define which mobs should spawn. (Default: "true" for all mobs.)
	[World.Mob_Spawning]
		Hunter = true
		Zebra = true
		Frog = true
		Jungle_Creeper = true
		Frozen_Zombie = true
		Muddy_Pig = true
		Duck = true
		Lost_Miner = true
		Camel = true
		Desert_Bandit = true

#Disable Enchantments from Better Default Biomes. (Default: "true" for all Enchantments.)
[Enchanting]
	#Horse Protection Enchantments like the Vanilla Protection Enchantments for the Player.
	enable_horse_protection = true
	#Thorns for Shields.
	enable_spikes = true
	#Mobs in a small area around the Player get the Glowing effect.
	enable_scout = true
	#Bows/Crossbows do more damage against animals.
	enable_hunting = true
	#Horses float in water.
	enable_floating = true
	#Knockback for Shields.
	enable_guard = true

	[Enchanting.Smelting_Touch]
		#Smelt blocks when mining.
		enable_smelting_touch = true
		#Sets Mobs/Players on fire when attacked.
		set_on_fire = true

#Item configurations for Better Default Biomes. (Default: "true" for all settings.)
[Item]

	[Item.Torch_Arrow]
		#Set Mobs/Players on fire when hit by a Torch Arrow.
		set_on_fire = true

#Trading configurations for Better Default Biomes. (Default: "true" for all settings.)
[Trading]
	#Enable trades added by Better Default Biomes.
	enable_trades = true

#Extensive Config options for all the Mobs.
[Mobs]

	#Config options for the Hunter and Variants.
	[Mobs.Hunter]
		#Spawn Biomes/BiomeCategories where the Hunter will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["jungle"]
		#Drop chance for the "Hunter's Bow" (Default: 8)
		#Range: 0 ~ 200
		drop_chance = 8
		#Spawn weight for the Hunter. (Default: 90)
		#Range: 0 ~ 10000
		weight = 20
		#Maximum amount of Hunters to spawn in a group. (Default: 3)
		max_group = 3
		#Minimum amount of Hunters to spawn in a group. (Default: 1)
		min_group = 1

		#The Head Hunter is a special variant of the Hunter. It's even more deadly!
		[Mobs.Hunter.Head_Hunter]
			#Spawn weight for the Head Hunter. (Default: 10)
			#Range: 0 ~ 10000
			weight = 2
			#Enables the spawning of the Head Hunter. (Default: true)
			head_hunter = true

			#This is the interval between shots.
			[Mobs.Hunter.Head_Hunter.Firing_Speed]
				#Tweak the firing speed of the Head Hunter for the Hard Difficulty. (Default: 10)
				#For reference: The Vanilla Skeleton firing speed for the Hard difficulty is: 20.
				firing_speed_hard = 10
				#Tweak the firing speed of the Head Hunter. (Default: 20)
				#For reference: The Vanilla Skeleton firing speed is: 40.
				firing_speed = 20

	[Mobs.Zebra]
		#Spawn Biomes/BiomeCategories where the Zebra will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["savanna", "biomesoplenty:lush_desert"]
		#Spawn weight for the Zebra. (Default: 12)
		#Range: 0 ~ 10000
		weight = 12
		#Maximum amount of Zebras to spawn in a group. (Default: 4)
		max_group = 4
		#Minimum amount of Zebras to spawn in a group. (Default: 2)
		min_group = 2

	[Mobs.Frog]
		#Spawn Biomes/BiomeCategories where the Frog will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["swamp"]
		#Spawn weight for the Frog. (Default: 10)
		#Range: 0 ~ 10000
		weight = 10
		#Maximum amount of Frogs to spawn in a group. (Default: 4)
		max_group = 4
		#Minimum amount of Frogs to spawn in a group. (Default: 2)
		min_group = 2

	[Mobs.Jungle_Creeper]
		#Spawn Biomes/BiomeCategories where the Jungle Creeper will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["jungle", "biomesoplenty:undergrowth"]
		#Spawn weight for the Jungle Creeper. (Default: 90)
		#Range: 0 ~ 10000
		weight = 90
		#Maximum amount of Jungle Creepers to spawn in a group. (Default: 3)
		max_group = 3
		#Minimum amount of Jungle Creepers to spawn in a group. (Default: 1)
		min_group = 1

	[Mobs.Frozen_Zombie]
		#Spawn Biomes/BiomeCategories where the Frozen Zombie will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["taiga", "icy"]
		#Removes Vanilla Zombie Spawning in these Biomes. (Default: true)
		remove_vanilla_zombies = true
		#Spawn weight for the Frozen Zombie. (Default: 95)
		#Range: 0 ~ 10000
		weight = 95
		#Maximum amount of Frozen Zombies to spawn in a group. (Default: 4)
		max_group = 4
		#Minimum amount of Frozen Zombies to spawn in a group. (Default: 4)
		min_group = 4

	[Mobs.Muddy_Pig]
		#Spawn Biomes/BiomeCategories where the Muddy Pig will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["swamp"]
		#Removes Vanilla Pig Spawning in these Biomes. (Default: true)
		remove_vanilla_pigs = true
		#Spawn weight for the Muddy Pig. (Default: 10)
		#Range: 0 ~ 10000
		weight = 10
		#Maximum amount of Muddy Pigs to spawn in a group. (Default: 4)
		max_group = 4
		#Minimum amount of Muddy Pigs to spawn in a group. (Default: 4)
		min_group = 4

	[Mobs.Duck]
		#Spawn Biomes/BiomeCategories where the Duck will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["swamp"]
		#Spawn weight for the Duck. (Default: 10)
		#Range: 0 ~ 10000
		weight = 10
		#Removes Vanilla Chicken Spawning in these Biomes. (Default: true)
		remove_vanilla_chickens = true
		#Maximum amount of Ducks to spawn in a group. (Default: 4)
		max_group = 4
		#Minimum amount of Ducks to spawn in a group. (Default: 4)
		min_group = 4
		#This feature is disabled for now as it requires more testing.
		jockey = false

	[Mobs.Lost_Miner]
		#The Lost Miner spawns in all Biomes by default.
		#These Biomes/BiomeTypes will be removed from the Spawn List.
		remove_biomes = ["nether", "the_end"]
		#Drop chance for the "Miner's Pickaxe" and "Miner's Helmet" (Default: 8)
		#Range: 0 ~ 200
		drop_chance = 8
		#Spawn weight for the Lost Miner. (Default: 160)
		#Range: 0 ~ 10000
		weight = 160
		#Maximum amount of Lost Miners to spawn in a group. (Default: 3)
		max_group = 3
		#Minimum amount of Lost Miners to spawn in a group. (Default: 1)
		min_group = 1

	[Mobs.Camel]
		#Spawn Biomes/BiomeCategories where the Camel will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["desert"]
		#Spawn weight for the Camel. (Default: 1)
		#Range: 0 ~ 10000
		weight = 1
		#Maximum amount of Camels to spawn in a group. (Default: 3)
		max_group = 3
		#Minimum amount of Camels to spawn in a group. (Default: 2)
		min_group = 2

	[Mobs.Desert_Bandit]
		#Spawn Biomes/BiomeCategories where the Desert Bandits will spawn.
		#To add Biomes or Categories:
		#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
		spawn_biomes = ["desert"]
		#Spawn weight for the Desert Bandits. (Default: 90)
		#Range: 0 ~ 10000
		weight = 20

#Extensive Config options for all the Generation Features.
[Generation]

	[Generation.Trees]

		[Generation.Trees.Palm_Trees]
			#Generation Biomes/BiomeCategories where Palm Trees will generate.
			#To add Biomes or Categories:
			#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
			generation_biomes = ["minecraft:beach"]

		[Generation.Trees.Swamp_Willow_Trees]
			#Generation Biomes/BiomeCategories where Swamp Willow Trees will generate.
			#To add Biomes or Categories:
			#["Category 1", "Category 2", "Biome 1", "Biome 2", etc...]
			generation_biomes = ["swamp"]

#Debug options for Better Default Biomes.
[Debug]
	#Enables the "BetterDefaultBiomes (Extra Info)" files to be generated by the mod. (Default: false)
	extra_info_files = false

	#Logger options.
	[Debug.Loggers]
		#Enables a logger for more info about the removed vanilla spawns. (Default: false)
		remove_spawn_logger = false
		#Enables a logger for more info about the registered spawns of the Mobs with selected SpawnBiomes. (Default: false)
		spawn_logger = false
		#Enables a logger for more info about the registered spawns of the Mobs that spawn in all Biomes by default. This is separate to avoid spam. (Default: false)
		spawn_logger_all = false

	#Define which mobs should have the Glowing effect. (Default: "false" for all mobs.)
	[Debug.Glowing_Mobs]
		Hunter = false
		Zebra = false
		Frog = false
		Jungle_Creeper = false
		Frozen_Zombie = false
		Muddy_Pig = false
		Duck = false
		Lost_Miner = false
		Camel = false
		Desert_Bandit = false

**Comment by Xratedjunior** [comment]
The Jungle Creeper only spawns on Grass Blocks. I don't think that Biome has that in the Nether so that will probably be why they are not spawning.

**Comment by NixityNull** [comment]
> The Jungle Creeper only spawns on Grass Blocks. I don't think that Biome has that in the Nether so that will probably be why they are not spawning.

Is there any chance you could add a spawn block config?

**Comment by Xratedjunior** [comment]
Yeah I'll try to think of a solution.

**Comment by Xratedjunior** [comment]
Fixed in later versions of the mod. (Changed Mob spawn criteria)
