### ISSUE TITLE
Feeding Zebras main hand weapons when right click

### ISSUE THREAD

**Issue by kulflame** [Xratedjunior/Better-Default-Biomes#7]
Right clicking a Zebra while holding tetra greatsword in main and shortblade in offhand, fed my mainhand greatsword to the zebra. 

I was streaming so I was able to access the VoD and verify this actually happened. 
https://www.twitch.tv/videos/870390046?t=3150s

**Comment by Xratedjunior** [comment]
Yeah thank you for telling me. I'm working on it. Really sorry for the inconvenience.

**Comment by NixityNull** [comment]
I have also had this issue and was actually just about to report it. 

I can also confirm it works on all items rather than just weaponry. This includes both modded and vanilla items.

**Comment by Xratedjunior** [comment]
I think that I've fixed it in version 2.5.2, which I'll be uploading in just a few minutes.
